# Deploy devops/terraform/main.tf.
#
# You need to run devops/pipelines/terraform-setup.yml first in order to create
# a storage account for Terraform status.

name: Terraform-Deploy

trigger: none

variables:
- group: Terraform-Status

parameters:
- name: onlyPlan
  displayName: Execute only the Terraform Plan creation, do not Apply it
  type: boolean
  default: true


stages:
- template: templates/stages-terraform-deploy.yml
  parameters:
    environment: dev
    onlyPlan: ${{ parameters.onlyPlan }}

- template: templates/stages-terraform-deploy.yml
  parameters:
    environment: test
    onlyPlan: ${{ parameters.onlyPlan }}
