# Template for applying a previouly created Terraform plan.
#
# This template uses a deployment job, so if the environment does not exists
# it will automatically create a new environment in DevOps.
# Use this template only for non-ephemeral environments (do not use this for
# deploying PRs, for example).

parameters:
- name: environment
  displayName: Environment name used for the deployment
  type: string
- name: terraformRootModulePath
  displayName: Path where the main.tf file is
  type: string
  default: $(Build.SourcesDirectory)/devops/terraform
- name: terraformPlanArtifactName
  displayName: Terraform Plan artifact name
  type: string
  default: tfplan


jobs:
- deployment: terraformApplyJob
  displayName: Terraform Apply ${{ parameters.environment }}
  environment: ${{ parameters.environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        # Artifacts are automatically downloaded in a deployment job.

        - template: tasks-terraform-init.yml
          parameters:
            environment: ${{ parameters.environment }}
            terraformRootModulePath: ${{ parameters.terraformRootModulePath }}

        - template: tasks-terraform-apply.yml
          parameters:
            terraformRootModulePath: ${{ parameters.terraformRootModulePath }}
            terraformPlanPath: $(Pipeline.Workspace)/${{ parameters.terraformPlanArtifactName }}/tfplan
