# Steps needed in a job for destroying Terraform resources and workspace.

parameters:
- name: environment
  displayName: Terraform workspace name
  type: string
- name: terraformRootModulePath
  displayName: Path where the main.tf file is
  type: string


steps:
- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV2@2
  displayName: Destroy Terraform
  inputs:
    provider: azurerm
    command: destroy
    workingDirectory: ${{ parameters.terraformRootModulePath }}
    environmentServiceNameAzureRM: $(terraformDeployAzureRMServiceConnectionName)
    commandOptions: -auto-approve -input=false

- script: |
    # Selecting default workspace because you cannot delete the active workspace.
    terraform workspace select default
    terraform workspace delete ${{ parameters.environment }}
  workingDirectory: ${{ parameters.terraformRootModulePath }}
  displayName: Delete Terraform workspace
